### ISSUE TITLE
bug: Parent table in AWS for AWS Organizations Delegated Services

### ISSUE THREAD

**Issue by jsonpr** [cloudquery/cloudquery#11029]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

AWS Organizations Delegated Services has a parent relation of AWS Organizations Accounts, should this be AWS Organizations Delegated Administrators instead since Delegated Services will only exist for accounts that are delegated administrators?

https://github.com/cloudquery/cloudquery/blob/main/website/tables/aws/aws_organizations_delegated_services.md

https://github.com/cloudquery/cloudquery/blob/main/website/tables/aws/aws_organizations_delegated_administrators.md

### Expected Behavior

Possibly a different relation for delegated administrators and delegated services.

### CloudQuery (redacted) config

NA

### CloudQuery (redacted) logs

NA

### CloudQuery version

NA

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by bbernays** [comment]
The current relationship is not "wrong" it is just not the most "correct" implementation. Users will still get 100% of the data they are looking for but if `aws_organizations_delegated_services` was a relation of `aws_organizations_delegated_administrators` then CQ would be able to make fewer API calls because currently we are calling `ListDelegatedServicesForAccount` for every single account in the Org rather than just those that are `delegated_admins`.
