### ISSUE TITLE
Improve Release notes by only showing the dependency update once

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#11944]
Currently if a plugin has many prs that incrementally update a package from 1.0.1 --> 1.0.2 --> 1.0.3 --> 1.0.6 we show that as 3 separate changes. From a users perspective it would be more comprehensible if we just showed a single upgrade to 1.0.6

**Comment by erezrokah** [comment]
Currently our tooling maps a single commit to a single release log entry. I don't think it supports grouping multiple commits, so that would require understanding the context of each commit and how to group them.
For example our dependency updates release logs link to the original PR with the dependency update changelog.

An easy way to reduce this noise is to sync the dependency updates with our release schedule so we'd get fewer release log entries per a single up. Please let me know if my explanation makes sense

**Comment by erezrokah** [comment]
Going to close this as won't fix. I think the solution is to release the CLI when we intend to release plugins right after, otherwise we're just creating a noise of updates
