### ISSUE TITLE
feat: cloudquery server

### ISSUE THREAD

**Issue by BubbaJoe** [cloudquery/cloudquery#12125]
### Which problem is this feature request solving?

Hello,

I have sort of a weird request / inquiry today. I would like to use CloudQuery as a server. For example, I will send some configuration (JSON) by HTTP and the server will then do the sync.

I thought about using the CLI inside the program, but there is certain information / functional component that i would like to have more control over.

Reasons: I want to manage the scheduling and execution programmatically of many integrations. Not so different from how [airbyte](https://docs.airbyte.com/cloud/managing-airbyte-cloud/edit-stream-configuration#modify-streams-in-your-connection) does it.

### Describe the solution you'd like

This might already be possible, but i'm not so familiar with the application architecture so much.

It would be nice if i could import the library that the CLI uses and run some function(s) that does the sync, but i doubt it will be that simple.
functions
- download deps
- list tables
- sync tables
  - get logs
  - get status

### Pull request (optional)

- [X] I can submit a pull request

**Comment by yevgenypats** [comment]
Hey @BubbaJoe , This should be possible already if you are using Go in your program:

You just use the API directly - https://github.com/cloudquery/plugin-pb-go

Basically you implement your own CLI as the CLI is just a small scheduler that runs jobs depending on how our YAML is configured. 

If you are using a different language, it should also be possible because you can generate `https://github.com/cloudquery/plugin-pb-go` via `https://github.com/cloudquery/plugin-pb` to any other language via gRPC. but Go prob should be easier as it's tested and available already. 

BTW - would love to learn more about the use case!

**Comment by BubbaJoe** [comment]
Thanks @yevgenypats, I am checking the client sync command implemented [here](https://github.com/cloudquery/cloudquery/blob/main/cli/cmd/sync.go).

I see that there are lots of references to 'clients', but what's the server? And when/where is it started?

**Comment by yevgenypats** [comment]
@BubbaJoe so few notes:
1) If you are going to implement something like this then you can only use version [protocol 3 and above](https://github.com/cloudquery/plugin-pb/tree/main/plugin/v3) as this will make things much easier. It's our new protocol and it consolidates both sources and destination which makes client logic much simpler.
2) It is started in [`managedclient`](https://github.com/cloudquery/cloudquery/blob/main/cli/cmd/sync.go#L130) which is [here](https://github.com/cloudquery/plugin-pb-go/tree/main/managedplugin) - this downloads the plugins and starts the server in grpc mode so we can connect to it right after.
