### ISSUE TITLE
feat(aws): Improve error message on authentication failure

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#12169]
### Which problem is this feature request solving?

Right now when authentication fails aws throws: 

```
failed to create execution client for source plugin aws: no enabled accounts instantiated
```

which is confusing as it is not clear why `no enabled accounts instantiated` - what does this mean from users perspective? what is the action items? is it something with the config? Is it something with the authentication? 

### Describe the solution you'd like

a better error message would be:

```
Authentication failed. Please check your credentials.
```

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by bbernays** [comment]
This error is definitely ambiguous and does not help the user. I don't think we can use the error message suggested because there are a number of different scenarios that can lead to this error being displayed. We iterate through the full list of accounts provided by the user in parallel and we only return a terminal error if **all** of the accounts fail. All failure paths have a `warning` message that is logged.

This error message can occur for 2 main reasons:
1. Permissions error for assuming a role or unable to retrieve credentials
2. No enabled regions specified
