### ISSUE TITLE
Improve Communication of Permission Errors

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#1385]
in cloudquery/cq-provider-aws#955 user reported that they were missing specific resources even though they were using the `resource = ["*"]`. All of the logs and outputs clearly indicated that there were no errors and everything fetched successfully. In order to understand what was going on user had to rerun fetch with the `-v` argument.

CloudQuery needs to improve communication to user when there is a permission error. The communication needs to tell the user how to dig into the issue while not overly alarming them as in many environments there will be restrictions that don't enable the user to grab all resources which is perfectly valid.

**Comment by yevgenypats** [comment]
This should be fixed in v2 with consistent and structured logging. We report all errors from API in `warn` level with the original errors. We are not doing extra summary because this all depends on the user use-case and interest so it is best to create rules, filter with jq / Loki to look for whatever is interesting for each use-case and plugin (i.e permission errors, tables, etc...)
