### ISSUE TITLE
feat: Add Defender endpoints data to Azure source plugin

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#15544]
### Describe the resource

Requested by a user. We currently sync https://learn.microsoft.com/en-us/rest/api/defenderforcloud/assessments/list?view=rest-defenderforcloud-2020-01-01&tabs=HTTP#securityassessment but it seems the data from https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/api/get-assessment-software-vulnerabilities?view=o365-worldwide#161-request-example is more up to date and complete

### Use Case

Detect security vulnerabilities in machines

### Link to API documentation

https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/api/get-assessment-software-vulnerabilities?view=o365-worldwide

### Additional Context

Not sure if we can do this via the Go SDK client. It seems the authentication to this API is a bit different https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/api/exposed-apis-create-app-nativeapp?view=o365-worldwide (found that from a quick research so could be totally wrong)

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by candiduslynx** [comment]
I think we can point to [this doc](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/api/exposed-apis-create-app-webapp) in the table description for the users to be able to understand how the auth would work.

**Comment by candiduslynx** [comment]
I've checked the Azure repos in GitHub for the [defender code](https://github.com/search?q=org%3AAzure+Microsoft+Defender+for+Endpoint+language%3AGo+&type=code) + looked deeper into [`armm365securityandcompliance`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/m365securityandcompliance/armm365securityandcompliance) package (because the docs link to the `microsoft-365/security/defender-endpoint` part.

It seems that the only API we can use is the already present [`armsecurity`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/security/armsecurity) package.

Closing as not planned till the better API is available.
