### ISSUE TITLE
feat: DuckDB should work under Docker

### ISSUE THREAD

**Issue by disq** [cloudquery/cloudquery#15591]
### Which problem is this feature request solving?

DuckDB driver has some issues (and requires cgo) which makes it hard to compile statically. Even if we do, other issues pop up because of auto-downloaded extensions as mentioned [here](https://github.com/cloudquery/cloudquery/issues/15501#issuecomment-1845866177). Running it all in Docker in a controlled environment would alleviate these.

### Describe the solution you'd like

Provide DuckDB dest plugin as a Docker image.
Would also fix https://github.com/cloudquery/cloudquery/issues/14557

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by hermanschaaf** [comment]
I think we can close this now.

If you're hoping to run the DuckDB plugin in Docker: my main recommendation would be to use one of the `ubuntu` CLI images listed [here](https://github.com/cloudquery/cloudquery/pkgs/container/cloudquery), rather than the default `alpine`-based `cloudquery` images. `alpine` doesn't ship with the glibc libraries currently required by the DuckDB plugin.
