### ISSUE TITLE
Yandex Cloud provider publishing

### ISSUE THREAD

**Issue by valyankilyan** [cloudquery/cloudquery#1606]
Recently downloading yandex cloud provider via `cloudquery init` became unavailable. I suppose all we need to do is give you the link to the provider.
https://github.com/yandex-cloud/cq-provider-yandex

**Comment by bbernays** [comment]
Hi @valyankilyan - I am sorry that the Yandex cloud provider is not working with the latest Cloudquery releases. Are you the one of the maintainers for the Yandex provider?

**Comment by valyankilyan** [comment]
@bbernays  Yes, I am one of the maintainers.

**Comment by bbernays** [comment]
So I believe `cloudquery init yandex-cloud` isn't working in the latest cli because in cloudquery `v0.29.` we dropped support for using HCL as the configuration language. It means that the tags on the `Config` object in the client package need to be changed from `hcl:` to `yml`. On top of that the `Example()` needs to change from returning an HCL string to a `yml`

Here is the [link](https://github.com/cloudquery/cloudquery/blob/2138ae05b908ed77c7de02c2d3bd7030e04c8e77/plugins/source/aws/client/config.go#L26-L56) to the aws provider and how it handles yml now.


Just be aware we are working on a v2 rewrite that aims to continue to drastically reduce the complexity of the codebase. @yevgenypats can speak to how it will impact your provider.

Until your yandex provider can be updated users can use older versions of cloudquery cli (before 0.29)

**Comment by yevgenypats** [comment]
Hi @valyankilyan, We are sorry for the inconvenience and I suggest for now to use the older CLI. I know cloudquery wasn't really stable in the last 6 month and this is we are pushing a v2 hopefully next week where stability will be improved without major breaking changes anymore. 

So yeah my suggestion would be to use old CLI for now and wait a week or two to update the plugin to the new SDK - we will also try to help with that and open a PR that migrate the plugin to the new SDK.

**Comment by valyankilyan** [comment]
@yevgenypats, thank you for noticing. Are you going to release any major updates for the plugin-sdk in the near future?

**Comment by toufreach5** [comment]
Hello,

@valyankilyan pushes modifications (release 0.2.0) especially on config changes (from hcl to yml).
I still can't download provider, so what's next step ? 

Thanks.

**Comment by yevgenypats** [comment]
I think this PR https://github.com/yandex-cloud/cq-provider-yandex/pull/23 should solve it. @candiduslynx please help with merging this PR if needed (looks like some tests are failing)

**Comment by valyankilyan** [comment]
There aren't any tests, I'm working on it. After I've done with tests we will merge this PR

**Comment by yevgenypats** [comment]
I think this is solved now. Please reopen if not.
