### ISSUE TITLE
bug: Snyk Projects v1 API has been sunset in favor of Rest API

### ISSUE THREAD

**Issue by disq** [cloudquery/cloudquery#16225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`snyk_projects` not getting synked

### Additional Context

The API has been sunset in late 2023: https://docs.snyk.io/snyk-api/migrate-list-all-projects-v1-api-to-rest-api

Reported on [discord](https://discord.com/channels/872925471417962546/873606591335759872/1198973285862477945)

**Comment by candiduslynx** [comment]
@pilvikala is looking into asking Snyk for a proper SDK support (either in Go or Python/JS) for this API

**Comment by pilvikala** [comment]
I was recommended to use a code generator against their open API spec: https://api.snyk.io/rest/openapi/2024-01-23
There's PySnyk but I was told it's buggy and I also don't like the option of having to migrate this to Python because of how our Python plugins need to be deployed. It would make it more difficult to migrate to a newer version.

@disq is this something you could help with?
