### ISSUE TITLE
feat(cli-v2): Prompt the user for any required configurations during `gen` except in CI

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#1809]
### Is your feature request related to a problem? Please describe.

Most plugins requires additional items to be set in the configuration after generation (e.g. project Id, token).
I usually forget to update that field and only discover I forgot after I see a bunch of errors.

### Describe the solution you'd like

It would be nice if the CLI would prompt the user for any required fields and add them to the generated configuration.
This would probably require plugins to declare their requirements somehow (e.g. via a file).

In a non interactive environment we should skip the prompts and generate the configuration with values' placeholders

### Describe alternatives you've considered

Manually updating the configuration after I figure out I forgot to

**Comment by yevgenypats** [comment]
I don't think we should go into interactivity in the `gen` command. Good documentation is key and users run that in a k8s anyway so I would say the generate example is really good enough (as this isn't even available in most tools). It's just to be big of a project and a room for bugs where we need to focus on documentation really rather then interactivity because most people will actually want to create them manually. Suggest closing this as no-implement.

**Comment by yevgenypats** [comment]
Closing as we removed `gen` command and we focus on quality documentation which we need anyway. Previous discussion https://github.com/cloudquery/cloudquery/pull/2022
