### ISSUE TITLE
bug(tests): Occasional data race reported in the tests

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#18241]
This seems to have been happening for a while. One example run [here](https://github.com/cloudquery/cloudquery/actions/runs/9466087481/job/26076972929), another [here](https://github.com/cloudquery/cloudquery/actions/runs/9468562415/job/26085186694)

```
WARNING: DATA RACE
Write at 0x0000038a2388 by goroutine 1095:
  github.com/cloudquery/cloudquery/cli/cmd.NewCmdRoot.func1()
      /home/runner/work/cloudquery/cloudquery/cli/cmd/root.go:88 +0x9a
  github.com/spf13/cobra.(*Command).execute()
      /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:954 +0xd75
  github.com/spf13/cobra.(*Command).ExecuteC()
      /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x657
  github.com/spf13/cobra.(*Command).Execute()
      /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039 +0xa6
  github.com/cloudquery/cloudquery/cli/cmd.TestTables.func1()
      /home/runner/work/cloudquery/cloudquery/cli/cmd/tables_test.go:60 +0xa1
  testing.tRunner()
      /opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1595 +0x261
  testing.(*T).Run.func1()
      /opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1648 +0x44

Previous read at 0x0000038a2388 by goroutine 1085:
  github.com/rs/zerolog.(*Event).Timestamp()
      /home/runner/go/pkg/mod/github.com/rs/zerolog@v1.33.0/event.go:687 +0x1da
  github.com/rs/zerolog.timestampHook.Run()
      /home/runner/go/pkg/mod/github.com/rs/zerolog@v1.33.0/context.go:353 +0x3e
  github.com/rs/zerolog.(*timestampHook).Run()
      <autogenerated>:1 +0x17
  github.com/rs/zerolog.(*Event).msg()
      /home/runner/go/pkg/mod/github.com/rs/zerolog@v1.33.0/event.go:143 +0x103
  github.com/rs/zerolog.(*Event).Msg()
      /home/runner/go/pkg/mod/github.com/rs/zerolog@v1.33.0/event.go:110 +0x5fa
  github.com/cloudquery/cloudquery/cli/cmd.syncConnectionV3.func3()
      /home/runner/work/cloudquery/cloudquery/cli/cmd/sync_v3.go:267 +0x44c
  github.com/vnteamopen/godebouncer.(*Debouncer).invokeTriggeredFunc.func1()
      /home/runner/go/pkg/mod/github.com/cloudquery/godebouncer@v0.0.0-20240220152946-054f7dbbcf18/debouncer.go:124 +0xb8

Goroutine 1095 (running) created at:
  testing.(*T).Run()
      /opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1648 +0x845
  github.com/cloudquery/cloudquery/cli/cmd.TestTables()
      /home/runner/work/cloudquery/cloudquery/cli/cmd/tables_test.go:58 +0x1c4
  testing.tRunner()
      /opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1595 +0x261
  testing.(*T).Run.func1()
      /opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1648 +0x44

Goroutine 1085 (running) created at:
  time.goFunc()
      /opt/hostedtoolcache/go/1.21.5/x64/src/time/sleep.go:176 +0x44
```

**Comment by marianogappa** [comment]
Ok this is an annoying one. I'm pretty sure it's a "benign" race that is fixable but cumbersome.

Loggers are not thread-safe as per the author
https://github.com/rs/zerolog/issues/242#issuecomment-915611449

Which is not intuitive since their README doesn't say anything about that and most examples use the global logger
https://github.com/rs/zerolog/blob/master/README.md

In our code we use the global logger everywhere, e.g.
https://github.com/cloudquery/cloudquery/blob/2802209621f2f8de0311e0768a31989c3886d94c/cli/cmd/sync_v3.go#L85

Which uses
https://github.com/rs/zerolog/blob/master/log/log.go#L14

When we encode logs to JSON, we use this global var, and sometimes two goroutines are encoding logs at the same time:
https://github.com/rs/zerolog/blob/master/encoder_json.go#L16

When we set the `TimestampFunc` to use `time.Now` we're modifying this global, and in a different goroutine we might call it upon logging an event:
https://github.com/rs/zerolog/blob/master/globals.go#L108

And so we encounter races whenever two goroutines are reading/setting these fields (I just spot-checked a few but there are many different races). I don't think this is causing any issues; otherwise we'd see panics and/or garbled logs.

We can create non-global loggers like this everywhere to mitigate:
```
logger := zerolog.New(os.Stderr).With().Timestamp().Logger()
```
(this is the exact line that creates the global logger)

Alternatively, we could use a thread-safe logger library.

Do we want to fix this?

**Comment by marianogappa** [comment]
In all of the cases of races I can see, one of the two goroutines is producing a log message either via `.Msg` or `.Warn`, etc, and the other one is not, so I'm not convinced that this would fix the issue, but a different team has done this mitigation:

https://github.com/mskwon/clickhouse-backup/commit/2337090672a945207a589eccd3e8ab0a760791c7#diff-1fdbab9bbc83a9dd11d65842a5febe641bcecc1243a4cf2c76035ebf48347721R31

Essentially a one-liner that makes all global logger writes sequential via mutex. We could add it here:
https://github.com/cloudquery/cloudquery/blob/main/cli/cmd/logging.go#L50

Which just wraps the `io.MultiWriter`: `zerolog.SyncWriter(io.MultiWriter)`.

**Comment by marianogappa** [comment]
I took a second look at the races and one important observation is that, in all of them, one of the goroutines is the debouncer that logs the progress of the sync.

The progress reporter (which uses the debouncer) is supposed to trigger for the last time and wait when the sync finishes.

This could fail in two cases:
- Definitely if the sync finishes early with an error. If we test sync errors, definitely this can cause a race.
- There is a possible race condition even on a successful finish. The debouncer is in the OVERLAPPED configuration, so it could trigger one last time (trailing time) if it was just about to trigger in the goroutine when a channel is set to await it.

I'm submitting a PR that `defer`s a `.Cancel()` call that simply stops the timer, so it doesn't trigger again after the function finishes.

**Comment by disq** [comment]
I remember passing `logger` to everywhere in the cli trying to fix a race, which didn't fix it. Non-global loggers still fail at some point.
