### ISSUE TITLE
feature(v2): Improve progress bar

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#1828]
It took me a bit of time to understand that the left counter is total number of resources and the right one is the rate and that's the reason it's decreasing:

https://user-images.githubusercontent.com/26760571/190433528-fe0e3e20-28f2-442d-8735-5ef06fdc0150.mov

I suggest we drop the rate as I don't think it adds much value, and also remove the empty `/-` which I assume should be the total number (that we don't know in advance)

**Comment by yevgenypats** [comment]
This is done.

**Comment by erezrokah** [comment]
Let's discuss this a bit more. I don't think it's done as we still show unrelated information in the counter:
![image](https://user-images.githubusercontent.com/26760571/194744570-7a139535-a588-48f7-9616-1d0d35d66b6d.png)

See the additional `/-` (977 out of something) in the progress.

Removing the `/-` was also suggested in https://github.com/cloudquery/cloudquery/pull/2163

**Comment by yevgenypats** [comment]
I do like the `resource/sec` as it helps understand if the plugin is stuck on slow resources - I don't think we should remove extra information.

Regarding the `977/-` I think it's a nit and it is useful in some sense that we cannot now how much resources there are.
I would say we can def improve it but it is a low priority because we had bunch of issues with the old implementation and it had bigger issues like my terminal stopped working after every run and I had to revert - https://github.com/cloudquery/cloudquery/pull/2089

**Comment by erezrokah** [comment]
Sure so let's close as won't fix due to low priority
