### ISSUE TITLE
Discussion: Testing strategies for the CLI

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#1860]
Extracting the discussion from https://github.com/cloudquery/cloudquery/pull/1848 to an issue.

With the move to v2 we should think of a strategy on how to test CLI commands and integration with plugins.

Some ideas from the PR on how to setup the tests:
1. Run Cobra commands directly via code
2. Invoke the CLI as an external process

Some ideas from the PR on how to assert the tests:
1. Snapshot CLI output (not included in the PR)
2. Assert other CLI command side effects, like generated configurations (already exists in our existing tests)

Dump any thoughts you have, for example https://medium.com/@sapegin/whats-wrong-with-snapshot-tests-37fbe20dfe8e

**Comment by yevgenypats** [comment]
I think we should only use it via `code` as otherwise it will turn into implementing language constructs on top of stdout parsing. Also we shouldn't compare stdout as we are not using stdout as public api (i.e it's not a frontend) it's just a minimal cli showing a progress bar. what we want to check is that the functionality is there:
- errors code on incorrect parameters
- success on correct configuration
- downloading of plugins works
- sync works and returns data

the stdout comparison is really not something we want to maintain

**Comment by erezrokah** [comment]
I don't feel strongly about the stdout part. Running the CLI as an external process is a simple way to achieve tests isolation.
If we can find a way to do it via direct code invocation I'm good with that (last time I tried, in order to run the command directly via code, I had to setup a go module which means coping a bunch of files to a temp directory, but maybe there's another way to do it).

**Comment by yevgenypats** [comment]
I would keep the test as simple as that:
https://github.com/cloudquery/cloudquery/blob/main/cli/cmd/sync_test.go

The only addition I would add is once we have a destination csv plugin I would use it in the test instead of destination test plugin (as it's basically a /dev/null) and will check that the csv contains the information from the test source plugin.

**Comment by erezrokah** [comment]
Agree. With only one command (sync), looks like we don't need to add more tests at the moment.
Once we do, we can re-visit this
