### ISSUE TITLE
Consider making `version` configuration required and not default to `latest`

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#2054]
With the removal of the `gen` command we're now defaulting to `latest` for the plugin version configuration, which brings us back to https://github.com/cloudquery/cloudquery/issues/908.

Since `latest` is the default, and knowing that most users don't change the default, keeping it will prevent us from updating plugins without breaking existing versions of the CLI.

For starts, we could make it a required configuration (and thus clean the code that resolves the latest version from the CLI), and figure out a mechanism to help users get the latest version after the release of v1.

**Comment by yevgenypats** [comment]
Im good with making this a required field. 

We can in the future bring back the `gen` command but it will be just for this use-case as we have to be clear about the purpose of it. Also before that the `gen` command worked with `grpc` and `local` and also served for stub documentation.

We can make it very simple for the purpose when interacting with official and community plugins on github outputing the required version so it will be something like this

```
kind: source
spec:
  name: "aws"
  version: "v0.1.1"
  spec:
     # See plugin for documentation
```

Because before that we had quite a lot of code there: https://github.com/cloudquery/plugin-sdk/pull/169/files 
and seems like in development or local there is no need for this and really the only place where it can save some time is to get the latest version.

**Comment by hermanschaaf** [comment]
I wonder if we're opening ourselves to a bit of trouble by letting users choose different versions of the same plugin within a single `sync`. For example, you could have `cfg/aws1.yml` and `cfg/aws2.yml` both specifying different plugin versions, and then call `sync cfg`. I don't think there's any good reason for us to support that, and maybe we should throw an error if we find this to be the case.

A further thought is that we can look at `go get` as inspiration... It allows you to download and set the latest version initially, then also update it later.

So one idea is to keep the config files as they are, but add a simpler `gen` command (maybe called `get`) that can be used like this:

```
cloudquery get aws
```

On first run it would generate a very simple `aws.yml` like @yevgenypats said. On second run it would update the version inside `aws.yml`, as well as in any other aws config files found in the current directory.

**Comment by cqgaurav** [comment]
Why not have a min_supported_client_version specified whenever we do a plugin update? (and the client can print deprecation/unsupported messaging if the latest version of plugin doesn't support the current version of the client)

**Comment by yevgenypats** [comment]
I think are solving a problem that we don't have yet so I would just keep the `gen` command very simple without going into the whole read everything and then update accordingly but rather just add a small validation to `SpecReader` that will detect different versions for the same plugin and will error out. The user will have to update it accordingly. 

Regarding not supported latest this is already done in https://github.com/cloudquery/plugin-sdk/pull/181

**Comment by yevgenypats** [comment]
version is now required.
