### ISSUE TITLE
Feature: Tables presets

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#2103]
### Is your feature request related to a problem? Please describe.

I would like to ensure I can run a specific policy after a sync

### Describe the solution you'd like

At the moment we support configuring either a `*` for tables, or specific table names.
It would be nice to be able to configure a preset of tables that map out to a policy so I don't have to figure out which tables I need to configure.

### Describe alternatives you've considered

When I want to run a policy, either sync all resources or look at the policy to know which tables to sync

**Comment by yevgenypats** [comment]
At the moment we take a data classic data engineering approach so I don't think we should go into SQL parsing direction and/or be a proxy to sql queries. I suggest the following:

1) document which tables are used in specific policy (if there is a tool that already does is from `psql/sql` then we can just do it in CI and that's it so user can just copy paste)
2) to ease the per table necessity we can maybe support glob like `ec2_*` so it will be easier for a user to specify big chunks of tables. This can also be a use-case let's say a user is interested in a policy but don't mind about some services so they can tweak it as they wish. 

Policy running is a pure-sql thing which we don't control so we don't want to get in the middle as the smallest change will break our tool due to something we didn't detect and we will have to support it rather then put it on the user as they are aware of what queries they changed, tables they added and so on. 

So to sum-up: If there is already a linter that reads sql and output tables, then great we can put it in CI and this can be also a good guideline for users on how to extract the tables from their queries. If there is no such a tool then I wouldn't developer one.

Also, did a bit of research on sql parsing - this is quite an impossible task if we really want to parse ASTs and so on as we will need to work with multiple SQL flavours and so forth.

The only easy and most reliable way to do it as far as I know is plain string/regex parsing so for that we will have to have an up-to-date list of tables somewhere as `json` a script that reads all of them and then checks if any of them appear in the policy files. It should be possible to write this script but that's the only feasible solution Im aware of atm.

**Comment by bbernays** [comment]
You could theoretically dynamically generate a list of tables used in a policy by running prepending `explain` to each query and then parsing the output. That was how the snapshot testing was able to just store the data needed for a specific query

**Comment by yevgenypats** [comment]
I thought about this a bit more but this problem is out of scope for CloudQuery - (i.e finding sql tables defined in psql files - is not CQ related).

The easiest way users can achieve this if anyone needs it is to run the following `grep`:

`grep -RohE "aws_[a-zA-Z_]* " ./policies`

This will output all `aws` tables the same can be done for `gcp` and if a user has other tables they can use similar technique.

**Comment by erezrokah** [comment]
I like this workaround. Lets close this issue for now as wont fix

**Comment by bbernays** [comment]
The above `grep` has 2 issues:
1. Finds instances like `aws_nacl_allow_ingress_rules` which is actually a view: `view_aws_nacl_allow_ingress_rules`
2. Does not include numbers so EC2, elbv2 and s3 do not get found


The following regexp should be more accurate:

`grep -RohE " aws_[a-zA-Z_0-9]* " ./policies`
