### ISSUE TITLE
Remote Fetching of Config from object Storage

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#2145]
In V0 users were able to store configs in s3 in order to decouple the image from config file

**Comment by yevgenypats** [comment]
As far as I understand this is a use case for ECS containers where it's quite hard to mount files - https://github.com/aws/containers-roadmap/issues/56

This is the library we previously used - https://github.com/hairyhenderson/go-fsimpl 
I've a few objections about that approach:
- it imports aws,azure,gcp,consul,vault APIs (and tha's for now)
- maintaining such a library will introduce quite a lot of overhead of maintenance just for because ECS doesn't support mounting files. 
- it will increase the size of the library significantly
- It will move the responsibility of moving the files (from wherever they are located) from the user to us (which is a pretty basic things). It will open up not only bugfixes but also feature requests (git, cloudflare r2) and so on. This basically introduce maintains in all aspects - development, on-going support upgrading, documentation and support.
- This will also complicate the UI as now we will need also a way to specify where to download from or at least a way to override as URL parsing is not ideal (i.e another flag)

To me it seems a better way would be to use the suggested workaround in the issue -  putting the config as environment variable.

**Comment by yevgenypats** [comment]
Closing as customers were able to work-around this and importing/testing/updating/retrying remote storage for config is a lot of development/documentation and support work. If more discussion is needed let's discuss synchronously with the team
