### ISSUE TITLE
Using ENV variable for HCL Postgres password

### ISSUE THREAD

**Issue by ekelson-bcove** [cloudquery/cloudquery#216]
Writing this issue as a more of a question than an issue.  I haven't seemed to got the ENV interpolation working for the Postgres password in the HCL file.  Curious if I am doing it correctly (see below).  Interesting, the same behavior occurs if you submit it via the CLI option using `--dsn`.

Cloudquery Version - Docker pull of 0.15.5

```  
connection {
    dsn = "host=172.17.0.2 user=postgres database=postgres password=$DB_PASSWORD sslmode=disable"
  }
```

Use case: Using ENV variables in conjunction with config maps for secure secret storage (as opposed to hardcoding in source code).

**Comment by roneli** [comment]
Hi,

You would require to put the full DSN inside the the environment var. You can either pass it with `CQ_DSN` or via --dsn argument.

Since CQ version v0.15.5 you can do the following to interpolate or use variables anywhere in the HCL config #211 

```
    connection {
    dsn = "host=localhost user=postgres password=${DB_PASSWORD} database=postgres port=5432 sslmode=disable"
  }
```

You would then set the env var `CQ_VAR_DB_PASSWORD = "my_pass"`

Hope this answers your questions, if you have any more feel free to open an issue here or in our community discord

**Comment by roneli** [comment]
Could be a bug on our end, with cap case on the env variable. Try the env variable with all lower case. Ran this with latest version locally (not in docker)

 connection {
    dsn = "host=172.17.0.2 user=postgres database=postgres password=${db_password} sslmode=disable"
  }

**Comment by MichaelTay0** [comment]
receiving the following error now

> 90m10:20PM�[0m INF ❌ Failed to initialize client. Error: parse "DSN redacted": invalid port ":&tbi-=8" after host
