### ISSUE TITLE
inspector findings taking long to load

### ISSUE THREAD

**Issue by nkannekanti132** [cloudquery/cloudquery#3203]
There are two tables for inspector_findings and cloudquery gets stuck for more than an hour for inspector findings
There is no data in inspector_findings table and data is present in inspector_findings_2 table

**Comment by erezrokah** [comment]
Hi @nkannekanti132 and thank for reporting this.

The reason we have two versions of `inspector_findings` is because AWS has two versions of that service:
1. [Amazon Inspector Classic](https://docs.aws.amazon.com/inspector/v1/userguide/inspector_introduction.html) which maps out to the `aws_inspector_findings` table
2. [Amazon Inspector](https://docs.aws.amazon.com/inspector/latest/user/what-is-inspector.html) which maps out to the `aws_inspector2_findings` table

Can you confirm you're using the second service?

As for the time it takes to sync the data, I think there's something we can do to improve and will post a PR with a fix soon.

**Comment by erezrokah** [comment]
A follow up on this, [I've increased the number of results we fetch per API call for Amazon Inspector Classic to 500](https://github.com/cloudquery/cloudquery/pull/3264) so that should speed things up for that service.

Unfortunately for the new Amazon Inspector we can only retrieve 100 findings at a time. Do you mind sharing how many you have? That could explain the time it take to sync those

**Comment by erezrokah** [comment]
Also, can you share if you see any errors in `cloudquery.log`?

**Comment by erezrokah** [comment]
Going to close this as stale pre my comments. @nkannekanti132 please respond if relevant and I'll re-open
