### ISSUE TITLE
Feature request: Fetch relationships between AWS IAM groups, policies, user, roles 

### ISSUE THREAD

**Issue by mvaerle** [cloudquery/cloudquery#34]
I'm trying to using Cloudquery to automate some AWS compliance work. For this task it's relevant to know which policies belong to which groups, which users belong to which groups, etc. In the end to answer the question who can access which resources.

Cloudquery can fetch these separate things, but not the relationships between them. In SQL terminology I guess that would mean join tables like `users_groups` that contains a row for each user, group pair.

**Comment by yevgenypats** [comment]
@mvaerle Thanks for bringing this up. I've released https://github.com/cloudquery/cloudquery/releases/tag/v0.8.2

New tables
```
aws_iam_user_groups
aws_iam_group_policies
aws_iam_role_policies
```

Let me know if that helps and/or if other data is missing.

**Comment by mvaerle** [comment]
@yevgenypats Wow that was fast. I took a bit of time because I wanted to make sure that it fully supports my use case, but it does! I can now use cloudquery to generate our aws compliance authorisation sheet.

One very minor suggestion might be to include the cloudquery `group_id` into the the `aws_iam_user_groups` join table. That will remove an extra join to `aws_groups` that I'm now only doing to convert the aws ids to cloudquery ids, since my actual goal is to join the `aws_iam_group_policies`. This might not be according to your design/architecture ideas, in which case I'm completely fine with doing one extra join, it doesn't cause any real issues.

Thanks a lot for building this!

**Comment by yevgenypats** [comment]
@mvaerle Thanks for the detailed response and the kind words:). Regarding your suggestion (If I understood) I think it will be easier for me to add the AWS `group_id` to `aws_iam_group_policies` due to how the gorm library works. I can add it if it helps?

Also, I'm really interested in the AWS compliance authorisation sheet? Is it something you can share? I'd love other users to be able to re-use this kind of stuff/queries. (If not that's totally understandable).
