### ISSUE TITLE
Add a matrix test for different test plugin versions

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#3487]
It would be good to have a matrix test that tests different versions of the source + destination test plugins with various versions of the CLI and makes sure it all still works as expected. This might be hard to do in practice, but we've seen some instances of bugs slipping through where (for example) a newer CLI doesn't work with older versions of the postgres plugin, even though we expected them to. So far it's mostly come down to changes in the GRPC protocol that were meant to be backwards-compatible.

One (not fully thought out) idea on how to determine which versions should be tested against which versions is to look at the SDK version being used by each. I believe we should expect any CLI + source + destination combination to work as long as all their (internal) SDK major versions match. In some cases it may work despite major versions differing, but we can't guarantee that, so we don't have to test that in the matrix.

**Comment by erezrokah** [comment]
> I believe we should expect any CLI + source + destination combination to work as long as all their (internal) SDK major versions match

That's a great idea 🚀. We probably need to [switch our SDK to a major version first](https://github.com/cloudquery/plugin-sdk/pull/311)

**Comment by yevgenypats** [comment]
I don't think we can do something better then the e2e tests here - https://github.com/cloudquery/plugin-sdk/tree/main/serve

As long as those e2e tests pass what it should ensure is that if a plugin compiles with an SDK it should work with all versions supported by the SDK as we follow the non breaking rules in protobuf. I think having matrix will be not feasible as result infinite amount of possibilities and little value as if it find bugs that weren't found in our e2e bugs it means our e2e tests are bad or we are doing something really wrong in our version bumping. In that case that we are doing something wrong I would say this is find for users to report us so we can fix instead of running the infinite matrix test.

**Comment by erezrokah** [comment]
Thanks for commenting @yevgenypats. I think the intent of this issue to catch bugs in supposedly non breaking changes of the protocol. For example a change in behavior instead of the API surface.

Agree it's hard testing against multiple versions and possibilities, or know in advance what to test.
Maybe we should have an easy way to add regression tests to what we fixed so at least we know the same issue won't happen in the future

**Comment by yevgenypats** [comment]
Closing as stale
