### ISSUE TITLE
Bug(cli): Redundant error message is printed on wrong command

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#3755]
### Describe the Bug

When running a wrong command a redundant error message is printed, in JSON format.
Example:
![image](https://user-images.githubusercontent.com/26760571/200319847-9d5f6f3e-94a4-44a0-9bd0-4e52af88e013.png)

### Expected Behavior

Only a single error should be reported to the console

### CloudQuery Version

`1.5.6`

### Steps to Reproduce

```
cloudquery test
```

**Comment by cychiang** [comment]
Hi @erezrokah, I looked at this issue, but I don't think it's a bug. It's more like two different libraries are doing the same thing.

The issue is combining two libraries' outputs:
* cobra 
* zerolog

`cobra` is trying to handle unknown command and print an error message in [here](https://github.com/spf13/cobra/blob/main/command.go#L1027), and result as follows: 
```
Error: unknown command "test" for "cloudquery"
Run 'cloudquery --help' for usage.
```

In the meantime, `zerolog` is trying to show the message in a formatting way with `.Msg()` function. 

We can remove the duplicate json message by removing the `.Msg()`. Unfortunately, removing messages from `cobra` seems impossible because it's a `Print` function and always be there if something is wrong from `cobra` side.  

If we remove the `.Msg()`, then we probably lose the beauty of it for other scenarios to understand the timelines and so on for logs. 

I probably won't consider it a bug because those are features from libraries 🤣 . What do you think?

**Comment by erezrokah** [comment]
Thanks for looking into it @cychiang. I think the underlying issue is that we try to use the logger before it was initialized, hence we print twice to `stderr`, instead of once by Cobra to `stderr`, and a second time by `zerolog` to the log file.

We can silence Cobra using `cmd.SilenceErrors = true`, but I do think we should keep that useful behavior.
I've opened a PR with another approach to silence `zerolog` until it is initialized here https://github.com/cloudquery/cloudquery/pull/3908.

Please let me know what you think
