### ISSUE TITLE
output requested tables as json

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#5003]
As a follow-up to this: https://github.com/cloudquery/plugin-sdk/pull/347

Should we have a CLI command that output all tables requested from a sync into `json` files. This starting to look handy especially in datalakes/data-warehouses where the process of syncing the csv,json files is outside cloudquery so there are some helper scripts that are needed to generate SQL command to be run periodically.

**Comment by hermanschaaf** [comment]
I would like to suggest a `cloudquery tables <source-plugin-name>` command with one or two formatting options.

### Plaintext

```
cloudquery tables aws
```

would output all the top-level tables in a format that could be copy-pasted into a config file:

```
- aws_accessanalyzer_analyzers
- aws_account_alternate_contacts
...
```

Later we can consider an option to also output child relations.

### JSON

```
cloudquery tables aws --format json
```

would output the tables as JSON, same as here https://github.com/cloudquery/plugin-sdk/pull/347

That's probably good enough for now, because for exploration and copy-pasting to config the plaintext option is nice, and for any automated purpose (like generating HTML, markdown, pipelines, whatever) users can use JSON.

**Comment by erezrokah** [comment]
I like @hermanschaaf's suggestion. There are plenty of tools to transform JSON into something else.
Also while we iterate on this we could add postfix this command with `(beta)` or something to denote we might change the output in a breaking way, WDYT? This could be something simple as mentioning it in the description of the command

**Comment by erezrokah** [comment]
Closing as won't fix for now pending users' requests. We have this support in plugins and if someone asks for it we can add to the CLI
