### ISSUE TITLE
Google Sheets plugin

### ISSUE THREAD

**Issue by cqgaurav** [cloudquery/cloudquery#5190]
https://developers.google.com/sheets/api/reference/rest
https://developers.google.com/sheets/api/quickstart/go

**Comment by hermanschaaf** [comment]
I think this will require some design (and possibly SDK changes), since it's a bit different from other source plugins. In other source plugins, it is usually clear what the tables and columns are, and these are pre-defined in the plugin, and you are able to select / skip tables in the config. I'm not sure what the equivalent would be for Google Sheets, and how we would expect that to work.

**Comment by cqgaurav** [comment]
True, i think we would need the ability for users to specify what columns they care about as part of plugin configuration, something i can see useful for other plugins like csv
