### ISSUE TITLE
Test out-of-memory (OOM) scenarios, and make sure log message / error in this case is as clear as possible

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#5196]
## Background 

It was recently reported that the `cloudquery` process stopped abruptly, but with no clear indication of what went wrong, other than a whole number of `context canceled` errors. After lots of debugging and a few iterations, we have concluded that this was most likely caused by an out of memory (OOM) exception. Moving the cloudquery process onto a bigger EC2 instance solved the problem.

## Recommendation

We should test scenarios where we expect memory limits to be exceeded, and ensure that the message reported back to the user is clear in this case. I believe the reason it's especially tricky to diagnose right now because it's often the *source plugin process* that gets killed by the OS, not the CLI process.

## Further Context

Link to original report on Discord: https://discord.com/channels/872925471417962546/873606591335759872/1047113237772107838

**Comment by yevgenypats** [comment]
I think re memory it can be really tricky basically we should add it to the troubleshoot guide as the one of the first things to check for. because let's say there is a watchdog sending kill -9  for anything that is eating memory either k8s or wherever cq is running there is no way to catch sigkill (-9)  so I dont think we can do anything here.

Unless the signal is being sent is catchable in that case we can catch it and add a log/print line
