### ISSUE TITLE
Storage Accounts HTTPS

### ISSUE THREAD

**Issue by code-vise** [cloudquery/cloudquery#5543]
### Why do you need this resource or plugin? Please describe.

We'd like to be able to Ensures HTTPS-only traffic is allowed to storage account endpoints. Some criteria we'd like to be able to check for Enabling the HTTPS-only flag ensures that Azure does not allow HTTP traffic to Storage Accounts. plugin checks two fields but db model has one field

Need enableHttpsTrafficOnly column for storage account.

**Comment by erezrokah** [comment]
Hi @code-vise can you link to the Azure API you're referring to? I think we already extracts this information https://github.com/cloudquery/cloudquery/blob/2ce06fc3f47e8842ba5a1c7b44a87c49564a24ca/plugins/source/azure/docs/tables/azure_storage_accounts.md?plain=1#L38

The reason for the naming difference is because we use the JSON tag for the column name which is different than the struct field:
https://github.com/Azure/azure-sdk-for-go/blob/db4a684919cd1bf5be1e1b9eaf1facc405ff25ad/services/storage/mgmt/2021-01-01/storage/models.go#L571

**Comment by code-vise** [comment]
@erezrokah yeah that makes sense. Actually cloudsploit plugin is that that field I just checked that field is not included in azure rest api response. So we don't need that anymore. Thanks for quick response. Cheers
