### ISSUE TITLE
Streamline what column changes are considered breaking

### ISSUE THREAD

**Issue by candiduslynx** [cloudquery/cloudquery#6043]
There are several types of column changes we can make, so we need to understand clearly what changes are considered 100% breaking:

| Change type | Breaking? | Reason |
| :--- | :--- | :--- |
| Adding a column |  `false` | Doesn't break any data consistency |
| Adding a column to a PK |  `false` | Doesn't break any data consistency |
| Removing a column from a PK |  `true` | May introduce PK conflicts in the data and lead to data loss |
| Removing a column |  `true` | Data loss |
| Changing composite PK columns order |  `false` | May change the partitioning, but otherwise, harmless |
| Changing column type | `true` | Unknown if we can migrate |

**Comment by erezrokah** [comment]
Linking https://www.cloudquery.io/docs/advanced-topics/migrations for context too

**Comment by erezrokah** [comment]
Also the code that does the migration in Postgres:
https://github.com/cloudquery/cloudquery/blob/44ca2db2e3ad84b41035cc3857e50fcbf2233d3e/plugins/destination/postgresql/client/migrate.go#L126

**Comment by bbernays** [comment]
Changing composite PKs can significantly impact performance... if a user has created a query that relies on it for a lookup rather than doing a full table scan

**Comment by candiduslynx** [comment]
@bbernays, so, should we mark PK column order change as breaking?

IMO, the order change is only a potential issue.
So, maybe, requiring extra notice in the release notes, but still not breaking?

**Comment by hermanschaaf** [comment]
I wanted to add one wrinkle to this: I think `Adding a column to a PK` should be considered breaking, just to be on the safe side. The reason is that otherwise we can have two separate steps that are non-breaking in isolation, but breaking together. 

For example:

1. PR 1 adds a new column. (non-breaking)
2. PR 2 makes the new column a PK. (non-breaking)

However, now we are in a situation where the column may have null values, and so the migration will fail. To be safe I think we should consider all PK changes (except ordering changes) breaking.

**Comment by candiduslynx** [comment]
@hermanschaaf maybe we should add `Adding new column to table & PK` a breaking change, but other 2 are non-breaking separately.

**Comment by hermanschaaf** [comment]
> maybe we should add Adding new column to table & PK a breaking change, but other 2 are non-breaking separately.

Hmm, then we would need to go through the minor version history every time a column is promoted to PK, to make sure the column wasn't newly added within that major version. Otherwise our major / minor versions lose meaning as you can get a breaking change by bumping two minor versions.

I'd rather keep it simple and have a rule that it's breaking whenever a column gets added to the PK.

**Comment by erezrokah** [comment]
I believe we can close this, the logic is implemented in https://github.com/cloudquery/cloudquery/blob/e380a0622363ff29021798b4455c84aa8b6af8d5/scripts/table_diff/changes/changes.go#L83. We can re-open if needed
