### ISSUE TITLE
Discussion: Align migration logic between destinations

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#6600]
### Context

Prerequisite for https://github.com/cloudquery/cloudquery/issues/6584 and related to https://discord.com/channels/872925471417962546/1062341270955110501.

Currently our auto migration logic differs between destinations, which leads to confusion on what's breaking, what's auto migratable and what user action is needed on each major version bump or migration failure.

### Current state (based on https://github.com/cloudquery/cloudquery/issues/6043)

| Change type | Breaking? | Reason | Auto migratable
| :--- | :--- | :--- | :--- |
| Adding a column |  `false` | Doesn't break any data consistency | [Yes](https://www.cloudquery.io/docs/advanced-topics/migrations#addition)
| Adding a column to a PK |  `false` | Doesn't break any data consistency | Yes, assuming the data exists and not `null` [we recreate the constraint](https://github.com/cloudquery/cloudquery/blob/6bab35d0546d289bdc57c9c8d741cd046bb79c97/plugins/destination/postgresql/client/migrate.go#L157)
| Removing a column from a PK |  `false` | Assuming the new PK is unique this should be OK | [Yes, we recreate the constraint](https://github.com/cloudquery/cloudquery/blob/6bab35d0546d289bdc57c9c8d741cd046bb79c97/plugins/destination/postgresql/client/migrate.go#L157)
| Removing a column |  `true` | Column will be `null` in future syncs | [Yes](https://www.cloudquery.io/docs/advanced-topics/migrations#removal), we don't drop the column
| Changing composite PK columns order |  `false` | May change the partitioning, but otherwise, harmless | [Yes, we recreate the constraint](https://github.com/cloudquery/cloudquery/blob/6bab35d0546d289bdc57c9c8d741cd046bb79c97/plugins/destination/postgresql/client/migrate.go#L157)
| Changing column type | `true` | Unknown if we can migrate | [Yes in Postgres](https://github.com/cloudquery/cloudquery/blob/24e03bde398ae845e12a0e8d2975d9b1d0c562f8/plugins/destination/postgresql/client/migrate.go#L139) (we drop and add the column), [No in BigQuery](https://github.com/cloudquery/cloudquery/blob/24e03bde398ae845e12a0e8d2975d9b1d0c562f8/plugins/destination/bigquery/client/migrate.go#L181), [Snowflake](https://github.com/cloudquery/cloudquery/blob/c5456a8f5cecb2471779a44053861106f673a7ac/plugins/destination/snowflake/client/migrate.go#L91) and [SQLite](https://github.com/cloudquery/cloudquery/blob/c5456a8f5cecb2471779a44053861106f673a7ac/plugins/destination/sqlite/client/migrate.go#L99) (we fail the migration)

We're mostly consistent except in type changes.

### Proposal

We should decide what to do when a column type changes (try to convert, drop+add or error) and do it for all destinations.
Once we align the migration logic we can provide better action items once the migration fails.
As a follow up we could suggest a `migrate --force` command that recreates the new schema with the potential data loss, otherwise it can be quite tedious to figure out from the changelog which tables/columns need to be changed/dropped.

Thoughts?

**Comment by yevgenypats** [comment]
Agree. I think it should be documented as well on the website under destinations/overview/migrations :

| Change type | Breaking? | Reason | Auto migratable
| :--- | :--- | :--- | :--- |
| Adding a column |  `false` | Doesn't break any data consistency | [Yes](https://www.cloudquery.io/docs/advanced-topics/migrations#addition)
| Adding a column to a PK |  `true` | Doesn't break any data consistency | best effort: Yes, assuming the data exists and not `null` [we recreate the constraint](https://github.com/cloudquery/cloudquery/blob/6bab35d0546d289bdc57c9c8d741cd046bb79c97/plugins/destination/postgresql/client/migrate.go#L157)
| Removing a column from a PK |  `false` | Assuming the new PK is unique this should be OK | [Yes, we recreate the constraint](https://github.com/cloudquery/cloudquery/blob/6bab35d0546d289bdc57c9c8d741cd046bb79c97/plugins/destination/postgresql/client/migrate.go#L157)
| Removing a column |  `true` | Column will be `null` in future syncs | [Yes](https://www.cloudquery.io/docs/advanced-topics/migrations#removal), we don't drop the column.
| Changing composite PK columns order |  `false` | May change the partitioning, but otherwise, harmless | [Yes, we recreate the constraint](https://github.com/cloudquery/cloudquery/blob/6bab35d0546d289bdc57c9c8d741cd046bb79c97/plugins/destination/postgresql/client/migrate.go#L157)
| Changing column type | `true` | Unknown if we can migrate | [Yes in Postgres](https://github.com/cloudquery/cloudquery/blob/24e03bde398ae845e12a0e8d2975d9b1d0c562f8/plugins/destination/postgresql/client/migrate.go#L139) (we drop and add the column), [No in BigQuery](https://github.com/cloudquery/cloudquery/blob/24e03bde398ae845e12a0e8d2975d9b1d0c562f8/plugins/destination/bigquery/client/migrate.go#L181), [Snowflake](https://github.com/cloudquery/cloudquery/blob/c5456a8f5cecb2471779a44053861106f673a7ac/plugins/destination/snowflake/client/migrate.go#L91) and [SQLite](https://github.com/cloudquery/cloudquery/blob/c5456a8f5cecb2471779a44053861106f673a7ac/plugins/destination/sqlite/client/migrate.go#L99) (we fail the migration)

**Comment by erezrokah** [comment]
Postgres work is being done in https://github.com/cloudquery/cloudquery/pull/7819

**Comment by erezrokah** [comment]
I think we can close this and open a new issue to go over all destinations and add support for forced migrate mode, as in https://github.com/cloudquery/cloudquery/pull/7819.

We can't really align migration logic between destinations, as each destination might require a different action based on the type of schema change, depending on the DB capabilities
