### ISSUE TITLE
feat: Add Redis state backend

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#6630]
Redis would make a good addition alongside the local backend we currently support for storing cursor state of incremental tables. The ability to store state remotely is especially useful in distributed or containerized environments.

This backend would need to be added to the plugin-sdk: https://github.com/cloudquery/plugin-sdk/tree/main/internal/backends

**Comment by bbernays** [comment]
I would hesitate to use redis as a persistence layer... In the past users had to change specific settings in order to make sure that all data was persisted to disk rather than being stored in-memory...

I would prioritize the various backends that Terraform supports:
- [postgres](https://developer.hashicorp.com/terraform/language/settings/backends/pg)
- [s3](https://developer.hashicorp.com/terraform/language/settings/backends/s3)
- [gcs](https://developer.hashicorp.com/terraform/language/settings/backends/gcs)
- [azure](https://developer.hashicorp.com/terraform/language/settings/backends/azurerm)
- [k8s](https://developer.hashicorp.com/terraform/language/settings/backends/kubernetes)
- [consul](https://developer.hashicorp.com/terraform/language/settings/backends/consul)

**Comment by hermanschaaf** [comment]
@bbernays True, though Redis has the big advantage that it can do performant updates. Unlike in terraform (I believe), for our state, we need to do frequent updates during the sync to make sure we don't lose progress if the sync fails for whatever reason. I'm guessing here, but Terraform probably only persists the state once per operation.

But you're right, we can prioritize some other backends before Redis, if it's hard to configure properly. Or alternatively, we can offer a guide on how to configure it. But in any case, let's open some more tickets for the ones we think should be high priority. Postgres is probably a good one, and S3 as well.

**Comment by bbernays** [comment]
How often do we need to checkpoint/ persist the last known state? Is the cost and complexity of checkpointing super often worth it compared to just checkpointing every couple of minutes? At worst we spend a couple of extra minutes resyncing data... which is still a huge improvement over resyncing everything...

**Comment by yevgenypats** [comment]
This is now available with SDK V4 where we can use all our destinations as state backends
