### ISSUE TITLE
Support for AWS Neptune as a Graph DB destination

### ISSUE THREAD

**Issue by jsonpr** [cloudquery/cloudquery#6800]
CloudQuery recently released a Neo4j destination.  There has been some interest to use AWS Neptune as another Graph database destination for ease of management of a graph DB cluster.

This was reported by a customer as a potential desired destination.

**Comment by disq** [comment]
AWS Neptune connection is possible using the Neo4j connector, with the `connection_string: "bolt+ssc://localhost:8182"` connection string (and an ssh tunnel / bastion host... or just run in the same VPC)... the `sc` in `bolt+ssc` signifies insecure connection (`tls.Config` with `InsecureSkipVerify`) because there's an outstanding Mac issue with Go 1.8[*](https://github.com/golang/go/issues/51991), it could work with just `bolt+s` if ran under EC2 as well but I just didn't test it yet.

We still get some protocol errors and so on, so the Neo4j connector needs a few tweaks here and there before it can be fully supported. I'll look into those next.

**Comment by disq** [comment]
Continued in https://github.com/cloudquery/cloudquery/pull/8842
