### ISSUE TITLE
How to perform transformations?

### ISSUE THREAD

**Issue by chavda-bhavik** [cloudquery/cloudquery#7154]
I was checking `cloudquery` and was really amazed by its working. I cannot find any relevant references on how to perform transformations on data coming from a `source`. I'm considering the following basic transformations,
![image](https://user-images.githubusercontent.com/50201755/214475871-cb64729d-ea3d-4b9a-b769-c54a2e07f4c7.png)

**Comment by yevgenypats** [comment]
Hi @chavda-bhavik ! Thanks for the issue. Can you elaborate a bit on what you mean transformation? The following is just plain queries on the raw data. If you need more advanced transformations you can take a look at [dbt](https://github.com/dbt-labs/dbt-core) which you can do after the data is in the database/datawarehouse

**Comment by chavda-bhavik** [comment]
Thanks, @yevgenypats for your reply. In some scenarios, We don't want to put the entire source into a destination. Either we want to select a few tables, a few records based on condition, or perform some transformation before we put source data into the destination. So that kind of facility is available? or does `cloudquery` only help in transferring data from source to destination?

**Comment by erezrokah** [comment]
Hi @chavda-bhavik, you can specify a subset of tables or skip tables via the `tables:` and `skip_tables` configurations. See https://www.cloudquery.io/docs/reference/source-spec#tables.
We don't support dynamic filtering of data before it gets to the destination.

The reason is that it's usually better to sync all the data, then apply transformations later. That way you don't need to re-sync every time you need a different transformation.
Also by doing transformations later down the pipeline you separate the concerns of syncing the data, and operating on it.

Please let me know if that makes sense and cover your use case.
If it doesn't, can you share an example transformation you'd like to perform?

**Comment by chavda-bhavik** [comment]
It makes sense @erezrokah, thanks for the explanation.
