### ISSUE TITLE
Parquet/ORC files for S3 destination

### ISSUE THREAD

**Issue by Barneyjm** [cloudquery/cloudquery#7220]
### Is your feature request related to a problem? Please describe.
Parquet/ORC files for S3 destination are recommended for Athena/other serverless access patterns due to their compression and columnar format. 

CSV and JSON file types require Athena to open the ENTIRE file, parse it all, and then query it to return results. this is expensive and slow. 

### Describe the solution you'd like
have the output file type `parquet` or `orc` available for the S3 destination

### Additional context
https://docs.aws.amazon.com/athena/latest/ug/columnar-storage.html

https://pkg.go.dev/github.com/apache/arrow/go/parquet

**Comment by hermanschaaf** [comment]
Thanks for raising this issue @Barneyjm! I'll keep this open because it relates specifically to S3, but implementation-wise there's overlap with https://github.com/cloudquery/cloudquery/issues/6708. If we implement support for Parquet/ORC in underlying the filetypes library, then the S3 plugin will automatically also gain this functionality.

**Comment by Barneyjm** [comment]
Dang I searched for "parquet" before creating this issue but didn't see any results. I'll take a look at implementing this weekend probably

**Comment by hermanschaaf** [comment]
Hi @Barneyjm 👋  Support for Parquet was added to S3 in this PR: https://github.com/cloudquery/cloudquery/pull/7726 and released in the S3 destination plugin [v2.1.0](https://github.com/cloudquery/cloudquery/pull/7514). Let us know how it goes if you try it out!
