### ISSUE TITLE
Review and Update CloudQuery Documentation for AWS Multiple Accounts

### ISSUE THREAD

**Issue by jsonpr** [cloudquery/cloudquery#7646]
A couple recent threads in Discord have been related to customer issues when running CloudQuery with multiple AWS Accounts.

**Comment by valerioj** [comment]
is there a way to see the Discord threads?

**Comment by valerioj** [comment]
thanks for the info. i have such a problem; we have an organization in AWS with some dozens of accounts; we supposed that ideally the table aws_organizations_accounts would be filled with data from the API Call [organizations.ListAccounts](https://docs.aws.amazon.com/organizations/latest/APIReference/API_ListAccounts.html)) (+ [organizations.ListTagsForResource](https://docs.aws.amazon.com/organizations/latest/APIReference/API_ListTagsForResource.html)), both calls addressed at the root account... but it seems that Cloudquery asks each individual account for its data.

First of all, we found this to be "sub-optimal" just because one can do 1-2 API calls and get all the info, if the calls are addressed to the root account...

But also (I suppose because of the way our organization is configured) these calls are just not permitted; we tried modifying the permission policies but nothing!

do you know if there is any way to configure CQ to ask the root account? i tried several configs and nothing...

**Comment by bbernays** [comment]
Hi @valerioj - Just so I fully understand... Are you attempting to sync all of the data for every account in your organization or are you trying to just populate the [`aws_organizations_accounts` table](https://github.com/cloudquery/cloudquery/blob/main/plugins/source/aws/docs/tables/aws_organizations_accounts.md)?


Also if you want to hop on our [discord channel](https://www.cloudquery.io/discord) we can assist you there in a more live chat sort of way.

**Comment by valerioj** [comment]
i'm just trying to populate the table `aws_organizations_accounts`

**Comment by bbernays** [comment]
Ok! Can you share your configuration file? And where are you running CloudQuery (eg EC2, CloudShell, ECS, Locally)?

**Comment by valerioj** [comment]
`org:
  admin_account:
    id: 'xxxxxxxxxxx'
  member_role_name: xxxxxxxxxx
regions: 
  - eu-central-1 
aws_debug: false`

the update jobs are cron jobs on openshift/kubernetes running on EC2 instances

**Comment by bbernays** [comment]
If you are only trying to populate the `aws_organizations_accounts` table you don't actually need to use the `org` functionality, because that is designed to allow you to sync the data from every account in the org.

Also the API `organizations.ListAccounts` isn't available in the `eu-central-1` region so that is why it is always empty.

This configuration should work to be able to populate the table with no other unexpected calls:
```
kind: source
spec:
  # Source spec section
  name: aws
  path: "cloudquery/aws"
  version: "v15.2.0"
  tables: ["aws_organizations_accounts"]
  destinations: ["postgresql"]
  spec:
    regions: 
      - us-east-1 
    aws_debug: false
    ```

**Comment by valerioj** [comment]
thanks for the tips! well, i don't want to "just populate the accounts table", i want to get, for example, a list of all EC2 instances or S3 buckets in all the accounts in the organization...

sorry for the misunderstanding, i didnt think that that was what you meant with "sync the data from every account in the org"

**Comment by yevgenypats** [comment]
Closing as stale
