### ISSUE TITLE
Azure Incremental Tables

### ISSUE THREAD

**Issue by tomtom215** [cloudquery/cloudquery#8043]
### Is your feature request related to a problem? Please describe.

The Azure source plugin currently does not support enough incremental tables.

### Describe the solution you'd like

Support for more Azure incremental tables, please

**Comment by bbernays** [comment]
@tomtom215 - What tables would you like to see support the incremental sync functionality?

**Comment by tomtom215** [comment]
@bbernays you're quick to respond! We're currently stress testing CloudQuery on some massive subscriptions so I will need to get back to you tomorrow to see after it finishes, but to keep this conversation moving, I think a very easy table to start would be https://github.com/cloudquery/cloudquery/blob/main/plugins/source/azure/docs/tables/azure_compute_skus.md
We've seen it reach 40-50 megabytes and it obvious it won't face massive changes from day to day

**Comment by hermanschaaf** [comment]
@tomtom215 For the Compute SKUs example, is there a field we could filter on to only retrieve the data that's changed since the last sync, or a way to tell whether there's been a change since the last sync (without fetching the data itself)? This is a requirement for a table to be made into an incremental table.

If this is not available, another strategy you may want to consider is to split your CloudQuery config file in two (or more) that are synced at different intervals. For example, you could have one config with tables that get synced daily, and another with tables that get synced weekly or monthly.

**Comment by tomtom215** [comment]
@hermanschaaf thanks for the perspective on this. You're right that there are not many means of incrementing the Azure tables. We will adopt the approach mentioned above and splitting our config file for syncs at different intervals and size. Thanks all!
