### ISSUE TITLE
Atlassian Jira Source connector

### ISSUE THREAD

**Issue by koltyakov** [cloudquery/cloudquery#8104]
Are there any plans adding Jira data source?

**Comment by yevgenypats** [comment]
Hey @koltyakov There are definitely plans! We are also looking for potential contributors or maintainers, we usually look for the official vendor but Jira doesn't have an official Go SDK (and actually no other official SDK as well). We reached out to the Jira Go SDK maintainer - https://github.com/andygrunwald/go-jira/issues/609 but didn't hear back yet (feel free to upvote). Also, If you are interested in helping maintain this, please let us know and we can help bootstrap that plugin!

**Comment by koltyakov** [comment]
Great to hear this. Thanks for the info @yevgenypats 

BTW, if you also have plans adding SharePoint as a data source/destination feel free reaching me, I have some expertise and maintaining Go library for SharePoint.

**Comment by yevgenypats** [comment]
@koltyakov https://github.com/koltyakov/gosip looks great! We are up to help with any requested plugin as long as there is someone who can maintain it (either community or vendor), as we can't maintain all of them and we putting a lot of dev work on improving our SDK. 

If you think Sharepoint plugin would be useful for you and the community (as you know this community and use-cases better) we would love to help with a first version. if you can create https://github.com/koltyakov/cq-source-sharepoint empty repo with empty README we can open a very first PR with a few resources of your suggestion (that are the most used/important ones).

**Comment by koltyakov** [comment]
Thanks! Sounds great!

Created the repository. Would love to contribute to such plugin.

SharePoint object model is vast however it's very common that lists and document libraries information is needed somewhere somehow outside. Yes, such tools as PowerBI have a native connector, but I guess extending and making it simple to use in a custom way can open many doors for the folks who don't have time writing something like https://github.com/koltyakov/spsync for a custom task.

**Comment by yevgenypats** [comment]
Nice, Thank you! We will try kick the tires on that relatively soon and open a PR for your review to see if we got right the usage around the APIs.

**Comment by yevgenypats** [comment]
Hey everyone! We released a very first version of the [Jira](https://www.cloudquery.io/docs/plugins/sources/jira/overview) plugin. Few important notes:

- This is our first premium plugin 50$ (one time payment).
- The reason this one is premium is due to the huge number of free/open source plugins we already maintain and we reached our capacity (while keeping the quality) so with new plugins we try a new business model of one time $X payment. 
 
The one time payment includes:
  - 6 months of support and free updates.
  - Unlimited access to all versions in those 6 months (even past the 6 months you can still access the plugin and those versions).

Closing this issue but feel free to reopen or open new issues with requests for new tables.
