### ISSUE TITLE
Need to run cloudquery with different AWS profile

### ISSUE THREAD

**Issue by ramasamy-t** [cloudquery/cloudquery#8680]
Use case

I have deployed cloudquery as Kubernetes Pod and I need to use this Pod to fetch data from multiple AWS Accounts

For the current account metadata,
1. Created a kubernetes serviceaccount which has permissions to AWS resources - view access

For multiple accounts,
Can we use ~/.aws/credentials file and creates profiles inside this for multiple aws account

In cloudquery sync command can we mention aws profiles like mentioned below

cloudquery sync aws.yml --profile "profile-name"

If this is not currently possible, is there any way to fetch details from multiple accounts?

**Comment by hermanschaaf** [comment]
Hi @ramasamy-t, this should be possible through configuration files rather than with a CLI option - have you seen the tutorial on [managing multiple accounts on AWS](https://www.cloudquery.io/docs/plugins/sources/aws/multi-account)? Also check out [AWS accounts configuration](https://www.cloudquery.io/docs/plugins/sources/aws/configuration#accounts). There are also quite a few related [how-to guides](https://www.cloudquery.io/how-to-guides), which may be relevant but it depends on your requirements.

**Comment by ramasamy-t** [comment]
@disq I used the same,
Let me tell my usecase

1. I run cloudquery in kubernetes pod , using service account Im able to connect to current AWS account
2. But in second case, If i want to select different AWS account, Im not able to do so. "AWS_PROFILE" environment variable is not taken by cloudquery

**Comment by bbernays** [comment]
@ramasamy-t - Can you share the logs and errors for when you ran `cloudquery` with the `AWS_PROFILE`?
