### ISSUE TITLE
Add a Sync Metadata Table

### ISSUE THREAD

**Issue by getglad** [cloudquery/cloudquery#8690]
### Is your feature request related to a problem? Please describe.
Presently, to observe a `sync`'s operational health, I have to parse the logs. At scale across multiple workers, I end up building out a dashboard that turns that log parsing into data tables and charts.

### Describe the solution you'd like
The summary data regarding a resource tuple such as `(account, region, resource)` that is in the logs could be written to the `destination` as a `SyncMetadata` artifact.

Also recording sync start and stops would be valuable.

### Describe alternatives you've considered
Presently I parse the logs for an AWS sync as below.

`parse @message "table sync finished client=*:* errors=* module=* resources=* table=*" as Account, Region,  Errors, tableModule, Total, tableName`

It works as a reasonable basis to produce a data table that looks like the below.

| timestamp | Account | Region | tableName | Total | Errors |
|---|---|---|---|---|---|
| v1 | v2 | v3 | v4 | v5 | v6 |

### Additional context
I've built some data tables around the errors such as

`parse @message "error=\"operation error *: *, *\" client=*:* module=* table=*" as Service, Action, errorMsg, Account, tableClientRegion, tableModule, tableName`

And for sync-level errors that cause the process to entirely bail out
`parse @message "Error: *" as errorMsg`

But IMO error lines in the `destination` are less valuable than the summary output - knowing that errors have occurred and that the logs should be examined.

**Comment by michalz-rely** [comment]
I think the issue https://github.com/cloudquery/cloudquery/issues/8146 is related

**Comment by erezrokah** [comment]
Hi 👋  For those watching this issue, we're working on a guide for parsing and observing CloudQuery logs using Datadog. You can see it here https://cloudquery-r4i7sxw4c-cloudquery.vercel.app/how-to-guides/datadog-observability (PR https://github.com/cloudquery/cloudquery/pull/10285), and we would love your feedback.

I also opened https://github.com/cloudquery/cloudquery/issues/10266 as a result, and we might add more fields to the logs base on use cases so they can be easily queries.

Please let us know if this could work for you to solve the same use case a sync metadata table solves. I would also point out that a sync metadata table might not work when CloudQuery fails to access the destination, or have any unexpected error during the sync.

**Comment by erezrokah** [comment]
Sorry for the late follow up, the official guide is here https://www.cloudquery.io/how-to-guides/datadog-observability

**Comment by erezrokah** [comment]
Hi 👋 Another update on this. We've launched a new preview feature to support OpenTelemetry, see the docs in https://www.cloudquery.io/docs/advanced-topics/monitoring#opentelemetry-preview and https://www.cloudquery.io/docs/reference/source-spec#otel_endpoint-preview.

All the latest sources support this feature.

Also this issue seems to overlap quite a bit with https://github.com/cloudquery/cloudquery/issues/4718, but I'll keep it open for comments.

Please respond with any feedback you have 🚀

**Comment by yevgenypats** [comment]
> Thanks @erezrokah - this OpenTelemetry support seems interesting. Will be taking a look.
> 
> To reiterate on the original ask - I do still think there is a lot of value in having CloudQuery submit the stats to the destination. Ergonomically, I dislike the requirement of having to source a separate system to know the stats of a particular run.
> 
> In the case of CQ destinations that can support query operations, my ideal state would be to aggregate a stats collection, or cross reference a CQ config `id` with another table.
> 
> In all cases, it would provide a static manifest of jobs that have been run, vs parsing logs on systems that are likely to purge logs after a period of time. I also think there is a strong value in having CloudQuery be a source of truth about these stats, vs trusting we are parsing logs correctly.
> 
> In general, there is a lot to like with the system, but this is a pain point.

Hey @getglad ! I'll weigh in here as I was researching some of the stats/workflow area recently. It's a tricky area because it starting to overlap with other orchestration tools and then we need to be careful not to implement them on one hand (as those features tends to grow very fast) and on the other still provide good out of the box capabilities.

How you are running cloudquery right now? Things like [Airflow](https://www.cloudquery.io/docs/deployment/airflow), [kestra](https://www.cloudquery.io/docs/deployment/kestra) or [argo workflows](https://argoproj.github.io/argo-workflows/) (if you are using k8s). This can solve the whole summary thing and kinda take it to the next level by having history/ui/logs/duration/failed vs pass and so on. What do you think?

**Comment by erezrokah** [comment]
A couple of updates regarding this issue:
1. Starting from CLI version [5.25.0](https://github.com/cloudquery/cloudquery/compare/cli-v5.24.0...cli-v5.25.0) you can pass the sync command a `--tables-metrics-location` flag that will periodically print per table summary to a file. Usage via `cloudquery sync ./directory ./aws.yml ./pg.yml --tables-metrics-location metrics.txt` for example.
2. Starting from CLI version [5.25.0](https://github.com/cloudquery/cloudquery/compare/cli-v5.24.0...cli-v5.25.0) and all plugins released in the past week, we've improved the OpenTelemetry traces and metrics we send. There's an updated guide in https://docs.cloudquery.io/docs/advanced-topics/monitoring, also with a Datadog integration and dashboard we provide, image below ⬇️ . The dashboard supports filters by plugin, table and client ID (usually AWS account/region, or GCP project, depending on the plugins you use).

![image](https://github.com/user-attachments/assets/6eea552d-d192-4a08-a7b2-c395729f922e)

**Comment by erezrokah** [comment]
OK so I think with `send_sync_summary:true` and the [new monitoring guides](https://docs.cloudquery.io/docs/advanced-topics/monitoring/overview) this issue is covered.

If that's not the case please comment and I'll re-open
