### ISSUE TITLE
feat: Sentry logging & anonymized metrics data collection

### ISSUE THREAD

**Issue by haris81** [cloudquery/cloudquery#9265]
### Which problem is this feature request solving?

Increased logging governance controls

### Describe the solution you'd like

Hi, Looking into the code I see references to sentry and data collection at the end to:  analyticsv1.cloudquery.io

a) Is there a way we can parameterize sentry data collection to enable / disable along with sentry URL parameters which are currently hardcoded. This is to allow local / custom sentry data collection

b) Sync summary metrics.. can it be parameterized as well (enable / disable) with custom endpoint for local implementations

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by erezrokah** [comment]
Hi @haris81, thanks for opening the issue. You can see our telemetry docs here https://www.cloudquery.io/docs/telemetry. They explain how to control what is being collected.
As to your requests:

a) Can you explain the use case for send Sentry data to another endpoint? Our Sentry reporting is targeted for internal errors/panics reporting, and we use it to discover and fix bugs. We can't guarantee anything on the stability of structure of the data so I don't recommend relying on it.

b) Same question, what's the use case for sending the metrics to another endpoint? Is this covered by https://github.com/cloudquery/cloudquery/issues/8690 and https://github.com/cloudquery/cloudquery/issues/8146? If the use case is observability we are thinking about that a lot, and will need to figure out what's the best way to expose that data (currently the solution is to parse our structured JSON logs)

**Comment by haris81** [comment]
Hi @erezrokah, Thanks for providing the telemetry doc link.. it addresses the options to disable data sharing and I am good for now. Regarding the requests

a) I am currently exploring custom plugin development using cloudquery and also have our own local sentry instance (which may be true for other organizations with firewalls that block non local sentry traffic).. since there is already sentry capability it will be good to parameterize the url / functionality so it can be leveraged internally on a need basis during development or even as a logging framework as the structure of data matures

b) Yes, the use case is around observability. Looks like the endpoint was recently parameterized via env variable CQ_ANALYTICS_HOST as part of this: https://github.com/cloudquery/cloudquery/pull/7756

FYI. Extending existing logging into a metrics type database table with details at a summary / source & destination plugin metadata / table level run time stats will be helpful for easier analysis of past executions..

**Comment by erezrokah** [comment]
Thanks for sharing @haris81! Custom plugin development is a great use case 🚀 

a) I believe you can provide a custom Sentry DSN, would that cover that use case? See example https://github.com/cloudquery/cloudquery/blob/d83dca19c2c48ffb4e7c70804dc8d8c07246b90c/plugins/source/aws/main.go#L11. Anything else you'd like to configure?

b) We're still discussion internally what's the best way to integrate observability. There are some gotchas to a metadata table, as what happens if we fail to write to that table? It might be better to "outsource" the data to external, known observability tools in a structured format, instead of a custom metadata table. Also we don't want to couple our own analytics (`CQ_ANALYTICS_HOST`) that we use to improve the product, with sync metrics/history like feature.
I hope that makes sense.

If my comment in a) satisfies your use case, and b) is covered by https://github.com/cloudquery/cloudquery/issues/8690, should we close this issue?

**Comment by haris81** [comment]
Thank you for the updates @erezrokah.

Will go ahead and close the request, and get back once I have more inputs during plugin development & sentry testing.
