### ISSUE TITLE
feat: Method for Defining hash of Entire record to be the PK

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#9423]
### Which problem is this feature request solving?

Some records have no subset of fields that uniquely identify a record, sometimes it is valuable to be able to store a hash of the entire record as the primary key. In those scenarios individual tables should not have to define their own resolver to do this as this should be a generic functionality that is used across many tables and plugins.

### Describe the solution you'd like

I thought at this should be implemented in the SDK as a column resolver but after investigating it further realized that it cannot be a column resolver because column resolvers get called in a non deterministic manner and also the hashing would need to get done after `PostResourceResolver` is evaluated as well as that to can update the record as well.

By generalizing this functionality in the SDK we can help users avoid using libraries like `hashstructure` which rely on go runtime implementations rather than methods that can be implemented in other languages
### Pull request (optional)

- [ ] I can submit a pull request

**Comment by yevgenypats** [comment]
Few thoughts:
- There might be use-cases where this solves de-duplication. but
- If there are tables with no clear pks it can cause a variety of issues:
   - There will be duplicates anyway and we just introduce un-necessary complex code and constraints. For example if there are fields that contains moving timestamps and anything else. It will result wrong `select count` with or without pks.
 - Also, important to note - those duplicates are just for the time of the sync.
 - Also, any internal changes will change the hash which will render the pk not useful on cloudquery updates. 

I don't know if there is a solution or what is the best way here but just wanted to specify the downsides here.

**Comment by erezrokah** [comment]
Adding to what @yevgenypats wrote, I'd rather if the hashing be explicit on specific fields and not implicit on all fields.

Being explicit has the following benefits:
1. It forces the developer to think about what makes an item unique instead of using a catch all logic
2. When a new field is added to the struct the hash doesn't change implicitly and we have to do it manually, and probably as a breaking change

Using hashing in general has other downsides as each time we change the hashing logic it's a breaking change (and for all plugins if we do it in the SDK). Also in order to understand what the value in that column means, users have to look at our hashing code.

I'd rather have a "use all columns as PK", or just set all columns as PKs instead of hashing. That solution should have a similar effect, and is more aligned with our current architecture I think.

**Comment by erezrokah** [comment]
Closing as stale/wontfix for now. If still relevant we can re-open when needed by a plugin
