### ISSUE TITLE
Add support for snyk “reporting/issues” endpoint

### ISSUE THREAD

**Issue by dbrtly** [cloudquery/cloudquery#9755]
### Which problem is this feature request solving?

In addition to the current 4 tables, I need the issues table at https://api.snyk.io/v1/reporting/issues as described at snyk.docs.apiary.io/#reference/reporting-api/latest-issues/get-list-of-latest-issues

### Describe the solution you'd like

The existing four tables work well. I’d this one to pop in next to the others like it was there all along. 

The api implements pagination so we should be able to pull the first page, get the total number of pages and call the remaining pages with concurrency. In a perfect world, we would somehow be able to measure time-to-remediation as the interval between a scan identifies a vulnerability and when it was scanned as fixed in the code but I’m not sure that exists in the data from Snyk. 

I would love to submit a pull request but I’m new to golang. I need help/guidance. 

### Pull request (optional)

- [X] I can submit a pull request

**Comment by hermanschaaf** [comment]
Hi @dbrtly :wave: 

Thanks for this, if you're willing to try your hand at a pull request we'd be more than happy to offer guidance. We have some fairly detailed documentation on the CloudQuery-specific things in our docs under [Creating a New Plugin](https://www.cloudquery.io/docs/developers/creating-new-plugin) as a starting point. I think you should be able to get pretty far by reading that and looking at some other examples that are similar to this case, without knowing anything about Go (assuming you can install Go and run the plugin locally 😃 )

In this case you'd be making a contribution to the existing Snyk plugin in the `cloudquery/cloudquery` repo, so for development you'd want to fork this repo and run the Snyk source plugin locally. (In short, you'd run `go build` or `go run main.go serve` in the directory and then set up the config as described in https://www.cloudquery.io/docs/developers/running-locally) 

If you want to hop onto [Discord](https://cloudquery.io/discord) I'd be happy to give more specific guidance there if you get stuck on anything. Or otherwise, feel free to open a draft PR and we can collaborate that way as well.
